from __future__ import annotations

CANONICAL_UNITS: set[str] = {
    "pcs", "m", "m2", "m3", "kg", "t", "l", "bag", "roll", "shift",
    # delivery & earthwork
    "trip", "t_km", "machine_hour", "km", "m3_loose", "m3_solid",
}

UNIT_ALIASES: dict[str, str] = {
    # --- existing ---
    "piece": "pcs",
    "pieces": "pcs",
    "шт": "pcs",
    "штук": "pcs",
    "штука": "pcs",
    "meter": "m",
    "meters": "m",
    "м": "m",
    "метр": "m",
    "метров": "m",
    "m2": "m2",
    "sq.m": "m2",
    "sqm": "m2",
    "м2": "m2",
    "кв.м": "m2",
    "кв.м.": "m2",
    "m3": "m3",
    "cu.m": "m3",
    "м3": "m3",
    "куб.м": "m3",
    "куб.м.": "m3",
    "куб": "m3",
    "kilogram": "kg",
    "кг": "kg",
    "ton": "t",
    "tonne": "t",
    "тонна": "t",
    "тонн": "t",
    "т": "t",
    "liter": "l",
    "litre": "l",
    "л": "l",
    "мешок": "bag",
    "мешки": "bag",
    "мешков": "bag",
    "рулон": "roll",
    "рулоны": "roll",
    "рулонов": "roll",
    "смена": "shift",
    "смены": "shift",
    "смен": "shift",
    # --- new: machine_hour ---
    "маш.час": "machine_hour",
    "маш.ч": "machine_hour",
    "маш-час": "machine_hour",
    "машино-час": "machine_hour",
    "машиночас": "machine_hour",
    "мч": "machine_hour",
    "machine-hour": "machine_hour",
    "mh": "machine_hour",
    # --- new: trip ---
    "рейс": "trip",
    "рейсов": "trip",
    "рейса": "trip",
    "ездка": "trip",
    # --- new: t_km ---
    "т.км": "t_km",
    "т*км": "t_km",
    "ткм": "t_km",
    "тонно-км": "t_km",
    "тонно-километр": "t_km",
    # --- new: km ---
    "км": "km",
    "километр": "km",
    # --- new: m3_loose ---
    "м3 рыхл": "m3_loose",
    "м3 рыхл.": "m3_loose",
    "м3 в рыхлом": "m3_loose",
    # --- new: m3_solid ---
    "м3 плотн": "m3_solid",
    "м3 плотн.": "m3_solid",
    "м3 в массиве": "m3_solid",
    "м3 в плотном теле": "m3_solid",
}
